/**
 * Created by puxiang on 2018/2/24.
 */
export const CHANGETEXT = 'CHANGETEXT';


export const FETCHING_DATA = 'FETCHING_DATA';
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS';
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE';

export const FETCHING_DATA1 = 'FETCHING_DATA1';
export const FETCHING_PERSON_SUCCESS = 'FETCHING_PERSON_SUCCESS';
export const FETCHING_PERSON_FAILURE = 'FETCHING_PERSON_FAILURE';